services:
  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"

  service-a:
    build:
      context: .
      dockerfile: service-a/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - service-b


  service-b:
    build:
      context: .
      dockerfile: service-b/Dockerfile
    image: service-b
    ports:
      - "8081:8081"
    environment:
      WEATHER_API_KEY: "b00b37ad939c4476bae184026253005"

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    volumes:
      - ./otel-config.yaml:/etc/otelcol/config.yaml
    ports:
      - "4317:4317"
      - "55681:55681"
